'''
NOTICE

This software was produced for the U. S. Government
under Basic Contract No. W15P7T-13-C-A802, and is
subject to the Rights in Noncommercial Computer Software
and Noncommercial Computer Software Documentation
Clause 252.227-7014 (FEB 2012)

 2016 The MITRE Corporation. All Rights Reserved.
'''
# -*- mode: ruby -*-
# vi: set ft=ruby :# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 2200, host: 22
  config.vm.network :forwarded_port, guest: 3515, host: 3515
  config.vm.network :forwarded_port, guest: 3516, host: 3516
  config.vm.network :forwarded_port, guest: 3517, host: 3517
  config.vm.network :forwarded_port, guest: 5601, host: 5601
  config.vm.network "private_network", ip: "192.168.50.10"  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "unfetter_analytic"
    
  
    # Don't boot with headless mode
    # vb.gui = true    # Tweak the below value to adjust RAM
    vb.memory = 2048
  
    # Tweak the number of processors below
    vb.cpus = 2
    # Use VBoxManage to customize the VM. For example to change memory:
    # vb.customize ["modifyvm", :id, "--memory", "1024"]

  end
  config.vm.provision :shell, :path => "resources/bootstrap.sh"
end
